char* quotes[] = {
    "Hello, IT here. Have you tried turning it off and on again?",
    "Well that's easy to remember! 0118 999 881 999 119 725... 3",
    "I'll just put it here with the rest of the fire.",
    "Ah, well. Prepare to put mustard on those words, for you will soon be consuming them along with this slice of humble pie that comes direct from the oven of shame, set at gas mark egg on your face. I sort of forget what I was talking about...",
    "I don't think our death ray is working. I'm standing right in it, and I'm not dead yet.",
    "I reject your reality, and substitute my own.",
    "Quack, damn you!",
    "Adam, the police officer says you need to drink more.",
    "If I had any dignity, that would have been humiliating",
    "Maybe it's a myth that methane is flammable. It's not a myth. We're just idiots.",
    "[in anticipation of a massive explosion] Jamie wants big boom.",
    "It's a beautiful day at the bomb range. Birds are singing, rabbits are hopping about... and pretty soon there's gonna be a big explosion.",
    "Am I missing an eyebrow?",
    "Oh, my God! This is more fun than should be allowed.",
    "Bow ties are cool.",
    "Brilliant!",
    "Allons-y!",
    "Run. Run you clever boy, and remember...",
    "Nah, never. Well, maybe.",
    "There are things waiting in the darkness. Creatures of metal, fire and blood. But he's out there, burning through time, facing a thousand dangers across the stars and never giving up.",
    "Space, the final frontier.",
    "When are ya gonna get off of that milk diet Laddy? Now Scotch is a real drink for a man. [Scotch was invented by a little old lady from Leningrad.]",
    "You'd make a splendid computer, Mr Spock.",
    "Beam me up, Scotty.",
    "There seems to be no sign of intelligent life anywhere...",
    "There's no such thing as the unknown- only things temporarily hidden, temporarily not understood.",
    "The next thing you'll know, I'll be talking to myself.",
    "I like this ship! You know, it's exciting!",
    "Engage!",
    "To boldly go where no one has gone before.",
    "Shut up, Wesley!",
    "Tea, Earl Grey, hot.",
    "This is mutiny!",
    "Whenever I'm about to do something, I think, \"Would an idiot do that?\" And if they would, I do not do that thing.",
    "Keep it simple stupid!",
    "Can I offer you a nice egg in this trying time?",
    "Every day it gets a little easier. But you gotta do it every day. That's the hard part. But it does get easier.",
    "Is your social worker in that horse?",
    "A life, Jimmy, you know what that is? It's the shit that happens while you're waiting for moments that never come.",
    "Clear eyes, full hearts, can't lose.",
    "It only takes a room of Americans for the English and Australians to realise how much we have in common.",
    "I have spent much of my life trying to please people, trying to be what they wanted me to be rather than what I actually wanted to be",
    "I have a cunning plan.",
    "As cunning as a fox who’s just been appointed professor of cunning at Oxford University.",
    "Boom boom boom boom. Boom boom boom boom.",
    "You're talking to yourself again. Yes, it's the only way I can be sure of intelligent conversation.",
    "Wibble"
    "But I DO, Baldrick, I DO!",
    "George, who’s using the family braincell today?",
    "Two spikes would be an extravagance.",
    "Alright, let's start with the basics. English is a non-inflected Indo-European language... ",
    "Only two things are infinite - the universe and human stupidity, and I'm not so sure about the universe.",
    "The only South African Past-time I know about is leaving the Country when it becomes a Democracy...",
    "Peter Cushing lives in Whitstable. I have seen him on his bicycle. I have seen him buying vegetables. Peter Cushing lives in Whitstable.",
    "He doesn't have beer goggles, he has Madeira Pince-Nez",
    "Why was the March Hare so important to the Aztecs",
    "It would be the act of a pessimist to call it the first world war that early!",
    "Money, you might as well eat it!",
    "Did you know they've taken gullible out of the dictionary?",
    "They say of the Acropolis, where The Parthenon is...",
    "It's terribly tidy. I have a woman in twice a week.",
    "I know you think you're doing a voice right now but that is actually how you speak.",
    "York; Largest plastic-bottomed lake in Europe."
};